export type SensorType = {
  sensor_ble_id: string
  owner_name: string
  gateway_ble_id: string
  owner_email: string
  business_name?: string
  assignee_emails?: string[]
  owner_phone: string
  business_address?: string
  activationThreshold?: string
  bluetoothAddress?: string
  tempCc: string
  lowTemperatureAlarmThreshold2: string
  lowTemperatureAlarmThreshold1: string
  magnetState?: string
  hwVersion?: string
  jsonrpc?: string
  returnToSleepDuration?: string
  odr?: string
  bootloaderVersion?: string
  flags?: string
  sensor_result?: string
  configVersion?: string
  passkey?: string
  highTemperatureAlarmThreshold2: string
  highTemperatureAlarmThreshold1: string
  deltaTemperatureAlarmTheshold: string
  useCodedPhy?: string
  resetCount?: string
  temperatureAggregationCount?: string
  lowTemperatureAlarm?: string
  deltaTemperatureAlarm?: string
  highTemperatureAlarm?: string
  sensor_lock?: string
  movementAlarm?: string
  networkId?: string
  sensor_location: string
  activeMode?: string
  sensorName?: string
  resetReason?: string
  connectionTimeout?: string
  txPower?: string
  temperatureSenseInterval?: string
  id?: string
  scale?: string
  advertisingInterval?: string
  firmwareVersion?: string
  batterySenseInterval?: string
  batteryVoltageMv?: string
  advertisingDuration?: string
  userId: string
}
